apiVersion: v1
kind: Service
metadata:
  labels:
    app: oauth-proxy
    svc: oauth
  name: oauth-proxy-service
spec:
  type: NodePort
  selector:
    app: oauth-proxy
  ports:
  - name: http-oauthproxy
    port: 4180
    nodePort: 30418
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oauth-acc
  labels:
    account: oauth
    svc: oauth
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: oauth-proxy
  name: oauth-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "oauth-proxy"
  template:
    metadata:
      labels:
        app: oauth-proxy
    spec:
      serviceAccountName: oauth-acc
      containers:
      - name: oauth-proxy
        image: "quay.io/oauth2-proxy/oauth2-proxy:v7.4.0" #7.2.0 stable
        ports:
        - containerPort: 4180
        args:
          - --session-store-type=redis
          - --redis-connection-url=redis://redis-service.default.svc.cluster.local:6379/2
          - --http-address=0.0.0.0:4180
          - --upstream="static://200"
          - --set-xauthrequest=true
          - --pass-host-header=true
          - --pass-authorization-header=true
          - --pass-access-token=true
          - --scope=kuserdata openid appclient
          - --skip-jwt-bearer-tokens
          - --pass-access-token=true
          - --whitelist-domain=*
          #- --session-cookie-minimal=true
          - --skip-oidc-discovery
          - --login-url=http://{{MY_SERVICE_IP}}/auth/realms/appcloak/protocol/openid-connect/auth
          - --redeem-url=http://keycloak-service.authzone.svc.cluster.local:8080/auth/realms/appcloak/protocol/openid-connect/token
          - --oidc-jwks-url=http://keycloak-service.authzone.svc.cluster.local:8080/auth/realms/appcloak/protocol/openid-connect/certs
          ##- --validate-url=http://keycloak-service.kcloak.svc.cluster.local:8080/realms/appcloak/protocol/openid-connect/userinfo
        env:
          # OIDC Config
          - name: "OAUTH2_PROXY_PROVIDER"
            value: "keycloak-oidc"
          - name: "OAUTH2_PROXY_OIDC_ISSUER_URL"
            #value: "http://keycloak-service.kcloak.svc.cluster.local:8080/realms/appcloak"
            #value: http://localhost:42561/realms/appcloak
            value: http://{{MY_SERVICE_IP}}/auth/realms/appcloak
            
          - name: "OAUTH2_PROXY_CLIENT_ID"
            value: "appclient"
          - name: "OAUTH2_PROXY_CLIENT_SECRET"
            value: "PPPCy6Nkl9AdA5DxdMALuoKeI3UqJTDp"
          # Cookie Config
          - name: "OAUTH2_PROXY_COOKIE_SECURE"
            value: "false"
          - name: "OAUTH2_PROXY_COOKIE_SECRET"
            value: "ZzBkN000Wm0pQkVkKUhzMk5YPntQRUw_ME1oMTZZTy0="
          - name: "OAUTH2_PROXY_COOKIE_REFRESH"
            value: "4m30s"
          #- name: "OAUTH2_PROXY_COOKIE_DOMAINS"
          #  value: "*"
          # Proxy config
          #- name: OAUTH2_PROXY_UPSTREAMS
            #value: "http://istio-ingressgateway.istio-system.svc.cluster.local:80/"
          #  value: http://127.0.0.1:42465/
          - name: "OAUTH2_PROXY_EMAIL_DOMAINS"
            value: "*"
          #- name: "OAUTH2_PROXY_WHITELIST_DOMAINS"
          #  value: "*"
          - name: "OAUTH2_PROXY_HTTP_ADDRESS"
            value: "0.0.0.0:4180"
          - name: "OAUTH2_PROXY_SET_XAUTHREQUEST"
            value: "true"
          #- name: OAUTH2_PROXY_PASS_AUTHORIZATION_HEADER
          #  value: "true"
          - name: OAUTH2_PROXY_SSL_UPSTREAM_INSECURE_SKIP_VERIFY
            value: "true"
          - name: OAUTH2_PROXY_SKIP_PROVIDER_BUTTON
            value: "true"
          - name: OAUTH2_PROXY_SET_AUTHORIZATION_HEADER
            value: "true"
          - name: OAUTH2_PROXY_REQUEST_LOGGING
            value: "true"
          - name: OAUTH2_PROXY_SHOW_DEBUG_ON_ERROR
            value: "true"
          - name: OAUTH2_PROXY_ERRORS_TO_INFO_LOG
            value: "true"
          - name: OAUTH2_PROXY_PASS_HOST_HEADER
            value: "true"