apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default  #name of the policy
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
    
#---
#apiVersion: security.istio.io/v1beta1
#kind: RequestAuthentication
#metadata:
#  name: jwt-token-req
#  namespace: istio-system
#spec:
#  selector:
#    matchLabels:
#      istio: ingressgateway
#  jwtRules:
#  - issuer: http://keycloak-service.kcloak.svc.cluster.local:5432/realms/appcloak
#    jwksUri: http://keycloak-service.kcloak.svc.cluster.local:5432/realms/protocol/openid-connect/certs