apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: default  #name of the policy
  namespace: istio-system
spec:
  mtls:
    mode: STRICT
    
#---
#apiVersion: security.istio.io/v1beta1
#kind: PeerAuthentication
#metadata:
  #name: politwo
  #namespace: appspace
#spec:
  #selector:
    #matchLabels:
      #app: api-two
  #mtls:
    #mode: PERMISSIVE