apiVersion: v1
kind: Service
metadata:
  name: keycloak-service
  namespace: kcloak
  labels:
    app: keycloak-service
spec:
  ports:
  - name: http-keycloak
    port: 8080
  selector:
    app: keycloak
  type: LoadBalancer
  #externalTrafficPolicy: Local
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: kcloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
      - name: keycloak
        image: quay.io/keycloak/keycloak:latest
        args: ["--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true start-dev"]
        env:
#        - name: DB_ADDR
#          value: postgres-service
#        - name: DB_DATABASE
#          value: keycloak
#        - name: DB_USER
#          value: p-user
#        - name: DB_PASSWORD
#          value: p-password
#        - name: DB_VENDOR
#          value: POSTGRES

        - name: KEYCLOAK_ADMIN
          value: "admin"
        - name: KEYCLOAK_ADMIN_PASSWORD
          value: "admin"
        - name: KC_PROXY
          value: "edge"
        - name: KEYCLOAK_LOGLEVEL
          value: DEBUG
        - name: WILDFLY_LOGLEVEL
          value: DEBUG
        - name: KC_HTTP_RELATIVE_PATH
          value: /auth/
        #- name: KC_HOSTNAME
        #  value: keycloak.xxx
        - name: PROXY_ADDRESS_FORWARDING
          value: "true"

        - name: KC_DB
          value: postgres
        - name: KC_DB_URL
          value: jdbc:postgresql://postgres-service.kcloak.svc.cluster.local:5432/keycloak
        - name: KC_DB_USERNAME
          value: p-user
        - name: KC_DB_PASSWORD
          value: p-password

        ports:
        - name: http
          containerPort: 8080
        readinessProbe:
          httpGet:
            path: /auth/realms/master
            port: 8080