apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
  namespace: kcloak
  labels:
    name: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      restartPolicy: Always
      containers:
      - name: postgres
        image: postgres
        imagePullPolicy: IfNotPresent
        ports:
        - name: pg-port
          containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: keycloak
        - name: POSTGRES_USER 
          value: p-user
        - name: POSTGRES_PASSWORD
          value: p-password
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        volumeMounts:
        - name: pg-vol
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: pg-vol
        hostPath:
          path: /host/p-data 
      #securityContext:
        #runAsUser: 1000
        #runAsGroup: 1000
        #fsGroup: 1000

---

apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: kcloak
spec:
  ports:
    - name: pg-port
      port: 5432
      targetPort: 5432
  selector:
    app: postgres