apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deplo
  labels:
    app: react-fend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: react-fend
  template:
    metadata:
      labels:
        app: react-fend
    spec:
      containers:
      - name: react-fend
        image: react-image
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
--- 
apiVersion: v1
kind: Service
metadata:
  name: react-service
spec:
  selector:
    app: react-fend
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      #nodePort: 30000 #Port in which this Service at its IP addr is going to accept requ
      #RAnge 30000-32767