apiVersion: v1
kind: PersistentVolume
metadata:
  name: mini-volume
  labels:
    usage: dbstorage
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 100M
  hostPath:
    path: /host/data
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-miniv
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 30M
  selector:
    matchLabels:
      usage: dbstorage